#!/bin/bash

red='\033[1;31m'
green='\033[1;32m'
yellow='\033[1;33m'
blue='\033[1;34m'
nocolor='\033[0m'

currentfolder=$(echo "${PWD##*/}")
read -p 'GitHub username: ' username
read -p "Repo name ($currentfolder): " name

if [ -z "$name" ]; then
    name=$currentfolder
fi

read -p 'Make the repo private? (true/false): ' isprivate

while [[ "$isprivate" != "true" ]] && [[ "$isprivate" != "false" ]];
do
    read -p 'Make the repo private? only "true" or "false": ' isprivate
done

status=$(curl -s -u $username https://api.github.com/user/repos -d '{"name":"'$name'", "private":'$isprivate'}' | grep "full_name")

if [ -z "$status" ]; then
    echo -e "${red}Sorry, try again later :(${nocolor}"
    echo -e "Verify your ${yellow}login data${nocolor} or check the repo name (${yellow}have to be unique${nocolor})"
    exit
else
    echo -e "${green}Congratulations it is a boy${nocolor}, his name is ${blue}$name${nocolor}"
fi

if git rev-parse --git-dir > /dev/null 2>&1; then
    :
else
    read -p 'This folder is not initialized with git. Do you want to initialize it? (Y/n)' initfolder
    if [ "$initfolder" = "S" ] || [ "$initfolder" = "s" ] || [ "$initfolder" = "y" ] || [ "$initfolder" = "Y" ]; then
        git init
    else
        echo Enjoy your repo!!
        echo Long live to Torvalds!!
        exit
    fi
fi

read -p 'Would you like to add the URL of the remote repo? (Y/n)' addrepo

if [ "$addrepo" = "S" ] || [ "$addrepo" = "s" ] || [ "$addrepo" = "y" ] || [ "$addrepo" = "Y" ]; then
    read -p 'Remote username (origin): ' remotename
    if ["$remotename" = ""]; then
        remotename="origin"
        echo Created remote user $remotename
        git remote add $remotename https://github.com/$username/$name.git
    fi
    read -p 'Do you want to do the first deploy rigth now? (Y/n)' deployconfirmation
    if [ "$deployconfirmation" = "S" ] || [ "$deployconfirmation" = "s" ] || [ "$deployconfirmation" = "y" ] || [ "$deployconfirmation" = "Y" ]; then
        read -p "Commit message: " message
        git add .
        git commit -m "$message"
        git push -u $remotename master
        echo "Done!!"
    fi
fi

echo Enjoy your repo!!
echo Long live to Torvalds!!
