#!/bin/bash

[ "$UID" -eq 0 ] || exec sudo "$0" "$@"
echo "Searching for bin folder..."
binfolder=$(echo $PATH | cut -d ":" -f 1)
sleep 0.2
echo "Bin folder found: $binfolder"
echo "Installing..."
sleep 0.2
sudo cp create-github-repo $binfolder
echo "create-github-repo is ready to use"